oceanbase/oceanbase.github.io

- README.md
- content/docs/deploy_oceanbase/init_server.md
> ADD README.

- content/docs/deploy_oceanbase/ocp/_index.md
> [featrue] 增加ocp目录

- README.md
> [fix] 修改README

- content/docs/operation_maintenance/replace_and_offline.md
- content/docs/operation_maintenance/scale_in_out.md
> 更新节点替换以及扩缩容

- docusaurus.config.ts
Update algolia application for searching documents
> chore(search): update search application

- src/theme/NavbarItem/DropdownNavbarItem/index.js
- src/theme/NavbarItem/DropdownNavbarItem/styles.css
- src/theme/NavbarItem/DropdownNavbarItem/styles.module.css
Do some hackings for original NavbarItem/DropdownNavbarItem. By now, add `dropdownItems` for common navbar item to enable sub dropdown menu.
> Feat: nested dropdown menu item

- docusaurus.config.ts
- i18n/en/code.json
- i18n/zh-Hans/code.json
- src/pages/index.tsx
> Fixed #45, [Bug]: unify all documents under the docs navigator bar

- docs/sig/AI/sig_members.md
> fix sig doc

- docs/sig/AI/sig_members.md
- docs/sig/miniob/sig_members.md
> add miniob sig contributors

- docusaurus.config.ts
> 修复一处文件地址错误

- src/components/Blogs/index.tsx
1. Fixed broken links in the index page due to blogs migration.
> Fixed broken doc links in the index page

- docs/sig/obdiag/intro.md
> Update obdiag sig intro.md

- docusaurus.config.ts
> 在 sidebar 中增加中文版 DBA 入门教程

- .github/workflows/build-website.yml
- package.json
- src/theme/DocPaginator/index.tsx
- yarn.lock
1. Took [gitalk](https://github.com/gitalk/gitalk) for comments.
2. Used [Github OAuth application](https://github.com/settings/developers) for authentication.
3. Added a workflow for website building.
> Integrate Gitalk as comment plugin for documents and blogs

- docs/user_manual/operation_and_maintenance/scenario_best_practices/chapter_01_multi_tenants/04_resource_isolation_within_a_tenant/02_cgroup_config.md
> fix a repo

- docusaurus.config.ts
> Added the entrance to oceanbase devhub

- docusaurus.config.ts
> Adjusted the navbar item for Data + AI

- docs/blogs/users/Kwai.md
Regarding the Market colleague's request, change the Kwai article's title.
> Change the title of the article of Kwai

- docusaurus.config.ts
> fix #229, remove duplicate menu button

- docs/user_manual/operation_and_maintenance/zh-CN/tool_emergency_handbook/odp_troubleshooting_guide/03_connection_diagnosis.md
- docs/user_manual/operation_and_maintenance/zh-CN/user_practice_co-construction/02_Best_Practices_for_Deploying_OceanBase_on_K8s.md
> fix some repos

- docs/blogs/tech/ob-openai.md
Add the doc on building the app with ob and openAI
> Add the doc on building the app with ob and openAI
